# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poke_history',
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ManyToManyField(related_name='pokee', to='poke.User'),
        ),
    ]
