# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_auto_20171103_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.AlterField(
            model_name='poke',
            name='poke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='poke.User'),
        ),
    ]
